name: cbj_remote_pipes
description: A simple command-line application.
version: 1.0.1
homepage: https://cybearjinni.com

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  # Utility classes to work with asynchronous computations.
  async: ^2.11.0
  # High performance, open-source universal RPC framework.
  grpc: ^3.2.4
  # Small, easy to use and extensible logger which prints beautiful logs.
  logger: ^2.0.2+1
  # Runtime library for protocol buffers support.
  protobuf: ^3.1.0
  # Simple, fast generation of RFC4122 UUIDs.
  uuid: ^4.2.1

dev_dependencies:
  # Collection of lint rules for Dart and Flutter projects
  lint: ^2.2.0
