name: cbj_remote_pipes
description: A simple command-line application.
version: 1.0.0
homepage: https://cybearjinni.com

environment:
  sdk: ^2.18.0

dependencies:
  async: ^2.8.2
  # High performance, open-source universal RPC framework.
  grpc: ^3.0.2
  # Small, easy to use and extensible logger which prints beautiful logs.
  logger: ^1.1.0
  # Runtime library for protocol buffers support.
  protobuf: ^2.0.1
  # Simple, fast generation of RFC4122 UUIDs.
  uuid: ^3.0.5

dev_dependencies:
  # Collection of lint rules for Dart and Flutter projects
  lint: ^1.8.1
